serato/sws-js-sdk

src/Identity.js, src/License.js, test/integration/IdentityTest.js, test/integration/LicenseTest.js
/me/products and /users/{user_id}/products endpoints
=> [WEB-2282] Add endpoints and their tests

package-lock.json, src/Identity.js, src/License.js, src/Service.js, test/integration/LicenseTest.js
put /me/licenses/authorizations/{authorization_id} and post /users/{user_id}/licenses/authorizations/{authorization_id} endpoints
=>  [WEB-2282] Add endpoints and their invalid tests

src/Ecom.js, test/integration/EcomTest.js
Please review and let me know if I missed anything. :-)
=> [WEB-2302] - Added /me/paymentmethods endpoint and unit tests

src/Ecom.js, test/integration/EcomTest.js
- Add method and tests for new delete payment method Ecom endpoint
=> [WEB-2298] Add Delete Payment Method endpoints

src/Ecom.js, test/integration/EcomTest.js
- Add the updatePaymentMethod() method the JS SDK
=> [WEB-2297] Add updatePaymentMethod() method

src/Ecom.js, test/integration/EcomTest.js
- GET /catalog/products (products in the catalogue, rather than the user's products)
Waiting on the controller to be implemented in ecom.
=> [WEB-2333] Add getCatalogProducts() (GET /catalog/products)

src/Ecom.js, test/integration/EcomTest.js
-  /catalog/products endpoint
No authentication for this endpoint.
=> [WEB-2333] /catalog/products endpoint

src/Ecom.js, test/integration/EcomTest.js
- Implementation for plan change requests and confirm endpoints
- Basic integration tests
=> [WEB-2545] Implementation for change subscription endpoints

src/Ecom.js, src/Identity.js, test/integration/IdentityTest.js, test/slow/integration/IdentityTest.js, test/slow/integration/LicenseTest.js
- This is a superset of https://github.com/serato/sws-js-sdk/pull/46
=> Plan Change request refactors

package.json, src/Profile.js, test/integration/ProfileTest.js
* Adds `Profile.updateAvatar` and `Profile.deleteAvatar` methods
* Bumps version to 1.5.0
=> Adds endpoints for avatar editing in Profile service

package-lock.json, src/Profile.js, test/integration/ProfileTest.js
- Also includes an audit of `npm` packages
=> Support for POST to survey endpoints

package-lock.json, package.json, src/Ecom.js, test/integration/EcomTest.js, test/spec/ServiceTest.js
- Major version has been changed due to the breaking interface/implementation changes
=> [WEB-3813] Update `getInvoice` to use new endpoint

package-lock.json, package.json, src/Notifications.js, test/integration/NotificationsTest.js
- Unit tests for some of the methods were not practical so they were omitted
- We will not merge this into master as we will be testing these changes as we integrate them in future stories. Once stability has been proven in the integration stories we will merge this into master.
=> DO NOT MERGE [WEB-4534] Implement methods that expose management notifications endpoints

src/Ecom.js, test/integration/EcomTest.js
=> Revert "WEB-5405 merge with Master"

src/Ecom.js, test/integration/EcomTest.js
=> Revert "Revert "WEB-5405 merge with Master""

src/Profile.js, test/integration/ProfileTest.js
Replace param country with param country_code in `Profile.updateProfile` method.
=> [WEB-5548]: Updated Profile.updateProfile

package-lock.json, src/Profile.js, test/integration/ProfileTest.js
Rename post_code request argument to postcode in updateProfile method
=> [WEB-5507]: rename argument in the Profile service

package.json, src/Rewards.js, src/Sws.js, test/integration/RewardsTest.js
=> [WEB-6126] - Rewards

package-lock.json, package.json
=> [WEB-9128] Fix runtime Dependabot alerts in Serato Websites

src/Identity.js, types/Identity.d.ts
- Add `password_last_updated` to User object in the Id service
NOTE: To be merged after https://github.com/serato/id-serato-com/pull/911
=> [WEB-8896] My Account: update description copy on 'Change password' section

package-lock.json, package.json
Update version in relation to #171
=> [WEB-8896] Update package version

src/Ecom.js, src/Service.js, types/Ecom.d.ts
1. make `updateCartCouponCode` function can have `coupon_code` as null
2. make `toBody` function has an `allowNullValues`  param
=> [WEB-9897] REST API - Remove the coupon from the cart

src/DigitalAssets.js, types/DigitalAssets.d.ts
Added `sendSoundpackDownloadLink` method to send soundpack download details to user's email
=> [WEB-9960] added sendSoundpackDownloadLink 

package.json
=> [WEB-9960] updated the version.

src/Ecom.js, types/Ecom.d.ts
- Update CartItem type to have price and base_price rather than total_amount and base_amount
=> [WEB-9755] Front end - displaying prepaid credit information on 'Order summary' card

src/DigitalAssets.js
Added new `/api/v1/me/log/downloads/applicationinstaller` endpoint support.
=> [WEB-10273] Added application installer downloads endpoint

package-lock.json, package.json
=> [WEB-10273] added 6.12.0 release version.

src/Profile.js, types/Profile.d.ts
Add `daw` and `product` values to user profile update endpoints - already existing in profile service
=> [WEB-10247] Download survey implementation in CMS

src/DigitalAssets.js
Added `resources/${resourceId}/download-email` endpoint.
=> [WEB-10251] Send download link" button implementation in the CMS

package-lock.json, package.json
=> Release 6.13.0

package.json, src/DigitalAssets.js, types/DigitalAssets.d.ts
Removed `sendSoundpackDownloadLink` method since its not used anymore
=> [WEB-10598] - CMS: Update Soundpack "Send a link later" endpoint

package-lock.json, package.json, src/Identity.js, types/Identity.d.ts
Changes made
* Added additional param `includeEmailHistory` which allows a user to also search historical records in the console app
[WEB-10574]:https://serato.atlassian.net/jira/software/c/projects/WEB/boards/207?selectedIssue=WEB-10574
[WEB-10574]: https://serato.atlassian.net/browse/WEB-10574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-10574]

package.json
Update version number in `package.json`
=> [WEB-10581] SWS JS SDK: Update SDK to allow use of Token Refresh Rotation

package-lock.json, package.json, src/DigitalAssets.js
Added support for new download/applicationinstaller endpoint
=> [WEB-11077]-Added support for new download/applicationinstaller endpoint.

package-lock.json, package.json, src/Ecom.js, types/Ecom.d.ts
Update Ecom in SDK - add new types ProductVoucherOrder, ProductVoucherOrderList, ProductVoucherBatch, FileType, Status and Language, as well as getProductVoucherOrders fn to be used in Console app.
=> [WEB-11152] - Product Batch tool UI: updates to Listing page

src/Ecom.js
=> [WEB-11152] 

package.json, src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
- Update SDK to implement the GET and PUT /productvoucherorders/:product_voucher_order_id (get one by ID and update).
=> [WEB-11153] - Product Batch tool UI: updates to Edit batch form

package-lock.json, package.json, src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
- Add blacklistProductVoucherOrders for Ecom service
- Add related tests
=> [WEB-9587] Product Batch - Implement "blacklist unowned" endpoint

src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
- Added create ('api/v1/productvoucherorders' POST) and generate ('/api/v1/productvoucherorders/:productVoucherOrderId/generate' POST) endpoints 
- Added new type, ProductVoucherBatchParams, to account for the id/quantity pairs that are submitted to the create endpoint.
- Added unit tests for new endpoints
=> [WEB-11151] - Updates to 'Create batch' form

package.json, src/Ecom.js
Update package.json version and fix lint errors
=> [WEB-11151] 

package-lock.json, package.json, src/Ecom.js, types/Ecom.d.ts
Replace `paymentGateway/token` endpoint
=> [WEB-11277] Update My Account to use the new endpoint for payment provider token

package-lock.json, package.json, src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
Add GET /productvoucherorders/:product_voucher_order_id/download endpoint and related
=> [WEB-11161] Product Voucher Order - Implement "download" endpoint 

src/Ecom.js
=> [WEB-11161] Product Voucher Order - Implement "download" endpoint

.github/workflows/build.yml, test/integration/EcomTest.js
Fix the Ecom tests that were broken due to the new implementation for the paymentGatewayToken method
=> [WEB-8993] Fix tests

package-lock.json, package.json, src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
add GET /vouchers/:voucher_id to ecom service
=> [WEB-11342] Console app: add ability to be able to search by 'voucher code'

package-lock.json, package.json, src/Ecom.js, test/integration/EcomTest.js, types/Ecom.d.ts
- Add `PUT /me/billingaddress` and `PUT /users/{userId}/billingaddress` endpoints
=> [WEB-11321] My Account uses new billing address endpoint when updating billing address

src/Ecom.js, types/Ecom.d.ts
=> [WEB-9007] Frontend - List all stored payment methods 

src/Ecom.js, types/Ecom.d.ts
Add `POST /v1/orders` endpoint to Ecom service
=> [WEB-11481] Complete successful Credit/debit card purchase in Express Checkout 2.0
